cc_binary(
    name = "open_netcdf_smoke",
    srcs = ["open_netcdf_smoke.cc"],
    deps = [
        "//tensorstore:spec",
        "//tensorstore/driver/netcdf:driver",
        "@abseil-cpp//absl/log:initialize",
        "@nlohmann_json//:json",
    ],
)

