$schema: http://json-schema.org/draft-07/schema#
$id: kvstore/gcs
allOf:
- $ref: KvStore
- type: object
  properties:
    driver:
      const: gcs
    bucket:
      type: string
      title: Google Cloud Storage bucket to use.
      description: |
        The Google Cloud account that is used must have appropriate permissions
        on the bucket.  If the bucket has `Requestor Pays
        <https://cloud.google.com/kvstore/docs/requester-pays>`_ enabled, either
        additional permissions are required or a separate billing project must
        be specified using `Context.gcs_user_project`.
    gcs_request_concurrency:
      $ref: ContextResource
      description: |-
        Specifies or references a previously defined
        `Context.gcs_request_concurrency`.
    gcs_user_project:
      $ref: ContextResource
      description: |-
        Specifies or references a previously defined
        `Context.gcs_user_project`.
    gcs_request_retries:
      $ref: ContextResource
      description: |-
        Specifies or references a previously defined
        `Context.gcs_request_retries`.
  required:
  - bucket
definitions:
  experimental_gcs_rate_limiter:
    $id: Context.experimental_gcs_rate_limiter
    description: |-
      Experimental rate limiter configuration for Google Cloud Storage reads and
      writes.
    type: object
    properties:
      read_rate:
        type: number
        description: |-
          The maximum rate or read and/or list calls issued per second.
          See <https://cloud.google.com/storage/docs/request-rate#ramp-up>
      write_rate:
        type: number
        description: |-
          The maximum rate of write and/or delete calls issued per second.
          See <https://cloud.google.com/storage/docs/request-rate#ramp-up>
      doubling_time:
        type: string
        description:
          The time interval over which the initial rates scale to 2x. The cases
          where this setting is useful depend on details to the storage buckets.
          See <https://cloud.google.com/storage/docs/request-rate#ramp-up>
        default: "0"
  gcs_request_concurrency:
    $id: Context.gcs_request_concurrency
    description: |-
      Specifies a limit on the number of concurrent requests to Google Cloud
      Storage.
    type: object
    properties:
      limit:
        oneOf:
        - type: integer
          minimum: 1
        - const: "shared"
        description: |-
          The maximum number of concurrent requests.  If the special value of
          ``"shared"`` is specified, a shared global limit specified by
          environment variable :envvar:`TENSORSTORE_GCS_REQUEST_CONCURRENCY`,
          which defaults to 32.
        default: "shared"
  gcs_user_project:
    $id: Context.gcs_user_project
    description: |
      Specifies a Google Cloud project to bill for Google Cloud Storage
      requests.  If a `project_id` is not specified, requests are
      billed to the project that owns the bucket by default.  For `Requestor
      Pays <https://cloud.google.com/kvstore/docs/requester-pays>`_ buckets,
      however, requests without a `.project_id` specified will fail
      unless the Google Cloud account has additional permissions.
    type: object
    properties:
      project_id:
        type: string
        title: |
          Google Cloud project id, e.g. ``"my-project"``.  The Google Cloud
          account that is used must have appropriate permissions to bill to the
          specified project.
  gcs_request_retries:
    $id: Context.gcs_request_retries
    description: |
      Specifies retry parameters for handling transient network errors.
      An exponential delay is added between consecutive retry attempts. The
      default values are appropriate for GCS.
    type: object
    properties:
      max_retries:
        type: integer
        minimum: 1
        description: |-
          Maximum number of attempts in the case of transient errors.
        default: 32
      initial_delay:
        type: string
        description: |-
          Initial backoff delay for transient errors.
        default: "1s"
      max_delay:
        type: string
        description: |-
          Maximum backoff delay for transient errors.
        default: "32s"
  url:
    $id: KvStoreUrl/gs
    allOf:
    - $ref: KvStoreUrl
    - type: string
    title: |
      :literal:`gs://` KvStore URL scheme
    description: |
      Google Cloud Storage-based key-value stores may be specified using the
      :file:`gs://{bucket}/{path}` URL syntax, as supported by `gsutil
      <https://cloud.google.com/storage/docs/gsutil>`__.

      .. admonition:: Examples
         :class: example

         .. list-table::
            :header-rows: 1
            :widths: auto

            * - URL representation
              - JSON representation
            * - ``"gs://my-bucket"``
              - .. code-block:: json

                   {"driver": "gcs",
                    "bucket": "my-bucket"}
            * - ``"gs://bucket/path/to/dataset"``
              - .. code-block:: json

                   {"driver": "gcs",
                    "bucket": "my-bucket",
                    "path": "path/to/dataset"}
