$schema: http://json-schema.org/draft-07/schema#
$id: kvstore/file
allOf:
- $ref: KvStore
- type: object
  properties:
    driver:
      const: file
    path:
      type: string
      title: Path to root directory on local filesystem.
    file_io_concurrency:
      $ref: ContextResource
      description: >-
        Specifies or references a previously defined
        `Context.file_io_concurrency`.
  required:
  - path
title: JSON specification of file-backed key-value store.
definitions:
  url:
    $id: KvStoreUrl/file
    type: string
    allOf:
    - $ref: KvStoreUrl
    - type: string
    title: |
      ``file://`` KvStore URL scheme
    description: |
      File-based key-value stores may be specified using the widely-supported
      :file:`file://{path}` URL syntax.

      .. admonition:: Examples
         :class: example

         .. list-table::
            :header-rows: 1
            :widths: auto

            * - URL representation
              - JSON representation
            * - :json:`"file:///tmp/dataset/"`
              - .. code-block:: json

                   {"driver": "file",
                    "path": "/tmp/dataset/"}
            * - :json:`"file://C:/Users/abc/dataset/"`
              - .. code-block:: json

                   {"driver": "file",
                    "path": "C:/Users/abc/dataset/"}
