$schema: http://json-schema.org/draft-07/schema#
$id: kvstore/grpc
title: Read/write key-value store using the tensorstore-specific gRPC protocol.
description: JSON specification of the key-value store.
allOf:
- $ref: KvStore
- type: object
  properties:
    driver:
      const: grpc
    address:
      type: string
      title: gRPC Service Address.
      description: |
        An address of the grpc service.
    timeout:
      type: string
      description: |-
        Timeout for requests to the gRPC service.
  required:
  - address
