$schema: http://json-schema.org/draft-07/schema#
$id: driver/cast
allOf:
  - $ref: TensorStore
  - type: object
    properties:
      driver:
        const: cast
      base:
        $ref: TensorStore
        title: Base TensorStore to convert.
      dtype:
        $ref: dtype
        title: |
          Specifies the data type under which to view the `.base` TensorStore.
    required:
      - base
      - dtype
examples:
  - {
      "driver": "cast",
      "dtype": "int32",
      "base":
        {
          "driver": "zarr",
          "kvstore": { "driver": "gcs", "bucket": "my-bucket" },
        },
    }
definitions:
  url:
    $id: TensorStoreUrl/cast
    type: string
    allOf:
      - $ref: TensorStoreUrl
      - type: string
    title: |
      :literal:`cast:` TensorStore URL scheme
    description: |
      Data type conversion may be specified using the :file:`cast:{dtype}`
      URL syntax.

      .. admonition:: Examples
         :class: example

         .. list-table::
            :header-rows: 1
            :widths: auto

            * - URL representation
              - JSON representation
            * - ``"file:///tmp/dataset.zarr/|zarr3:|cast:uint32"``
              - .. code-block:: json

                   {"driver": "cast",
                    "dtype": "uint32",
                    "base": {"driver": "zarr3",
                             "kvstore": {"driver": "file",
                                         "path": "/tmp/dataset.zarr/"}}
                   }
