cc_binary(
    name = "open_netcdf_smoke",
    srcs = ["open_netcdf_smoke.cc"],
    deps = [
        "//tensorstore:spec",
        "//tensorstore/driver/netcdf:netcdf_driver",
        "@abseil-cpp//absl/log:initialize",
        "@nlohmann_json//:json",
    ],
)
cc_binary(
    name = "open_netcdf_smoke",
    srcs = ["open_netcdf_smoke.cc"],
    deps = [
        "//tensorstore/driver/netcdf:netcdf_driver_skeleton",
    ],
)

cc_binary(
    name = "open_netcdf_smoke_ncdf",
    srcs = ["open_netcdf_smoke_ncdf.cc"],
    deps = [
        "//tensorstore/driver/netcdf:netcdf_driver_skeleton",
    ],
)
