load("//third_party/bazel_skylib/rules:common_settings.bzl", "BuildSettingInfo")

_TEMPLATE = """
// version is auto-generated by the BUILD file.

#ifndef V
#define V "{version}"
#endif  // V

"""

def _write_string_version_impl(ctx):
    ctx.actions.write(
        output = ctx.outputs.out,
        content = _TEMPLATE.format(version = ctx.attr.label[BuildSettingInfo].value),
        is_executable = False,
    )
    return [DefaultInfo(files = depset([ctx.outputs.out]))]

write_string_version = rule(
    implementation = _write_string_version_impl,
    attrs = {
        "out": attr.output(mandatory = True, doc = "The output file to write the version to."),
        "label": attr.label(mandatory = True, doc = "The label to tag the release with."),
    },
)
