$schema: http://json-schema.org/draft-07/schema#
$id: driver/tiff
allOf:
  - $ref: TensorStoreKvStoreAdapter
  - type: object
    properties:
      driver:
        const: tiff
      dtype:
        const: uint8
        description: |
          Optional.  If specified, must be :json:`"uint8"`.
      page:
        type: number
        default: null
        description: |
          If specified, read this page from the tiff file.
examples:
  - driver: tiff
    "kvstore": "gs://my-bucket/path-to-image.tiff"
definitions:
  url:
    $id: TensorStoreUrl/tiff
    type: string
    allOf:
      - $ref: TensorStoreUrl
      - type: string
    title: |
      :literal:`tiff:` TensorStore URL scheme
    description: |
      TIFF TensorStores may be specified using the :file:`tiff:`
      URL syntax.

      .. admonition:: Examples
         :class: example

         .. list-table::
            :header-rows: 1
            :widths: auto

            * - URL representation
              - JSON representation
            * - ``"gs://my-bucket/path-to-image.tiff/|tiff:"``
              - .. code-block:: json

                   {"driver": "tiff",
                    "kvstore": {"driver": "gcs",
                                "bucket": "my-bucket",
                                "path": "path-to-image.tiff"}
                   }
