$schema: http://json-schema.org/draft-07/schema#
$id: driver/png
allOf:
  - $ref: TensorStore
  - type: object
    properties:
      driver:
        const: png
      dtype:
        const: uint8
        description: |
          Optional.  If specified, must be :json:`"uint8"`.
      kvstore:
        $ref: KvStore
        description: |-
          Specifies the underlying storage mechanism.
      cache_pool:
        $ref: ContextResource
        description: |-
          Specifies or references a previously defined `Context.cache_pool`.  It
          is normally more convenient to specify a default `~Context.cache_pool`
          in the `.context`.
        default: cache_pool
      data_copy_concurrency:
        $ref: ContextResource
        description: |-
          Specifies or references a previously defined
          `Context.data_copy_concurrency`.  It is normally more
          convenient to specify a default `~Context.data_copy_concurrency` in
          the `.context`.
        default: data_copy_concurrency
      compression_level:
        type: number
        default: ""
        description: |
          Unused. PNG compression level.
    required:
      - kvstore
examples:
  - driver: png
    "kvstore": "gs://my-bucket/path-to-image.png"
definitions:
  url:
    $id: TensorStoreUrl/png
    type: string
    allOf:
      - $ref: TensorStoreUrl
      - type: string
    title: |
      :literal:`png:` TensorStore URL scheme
    description: |
      PNG TensorStores may be specified using the :file:`png:`
      URL syntax.

      .. admonition:: Examples
         :class: example

         .. list-table::
            :header-rows: 1
            :widths: auto

            * - URL representation
              - JSON representation
            * - ``"gs://my-bucket/path-to-image.png/|png:"``
              - .. code-block:: json

                   {"driver": "png",
                    "kvstore": {"driver": "gcs",
                                "bucket": "my-bucket",
                                "path": "path-to-image.png"}
                   }
